<a href="https://colab.research.google.com/github/Jegge2003/GoogleCollabTrials/blob/main/supervised_word_embeddings.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Flatten
from tensorflow.keras.layers import Embedding

reviews = ['nice food',
        'amazing restaurant',
        'too good',
        'just loved it!',
        'will go again',
        'horrible food',
        'never go there',
        'poor service',
        'poor quality',
        'needs improvement']

sentiment = np.array([1,1,1,1,1,0,0,0,0,0])

In [3]:
one_hot("amazing restaurant",30)

[19, 12]

In [4]:
vocab_size = 30
encoded_reviews = [one_hot(d, vocab_size) for d in reviews]
print(encoded_reviews)

[[26, 8], [19, 12], [1, 21], [7, 19, 23], [12, 1, 9], [22, 8], [5, 1, 28], [27, 23], [27, 15], [4, 26]]


In [6]:
max_length = 3
padded_reviews = pad_sequences(encoded_reviews, maxlen=max_length, padding='post')
print(padded_reviews)

[[26  8  0]
 [19 12  0]
 [ 1 21  0]
 [ 7 19 23]
 [12  1  9]
 [22  8  0]
 [ 5  1 28]
 [27 23  0]
 [27 15  0]
 [ 4 26  0]]


In [10]:
embeded_vector_size = 4

model = Sequential()
model.add(Embedding(vocab_size, embeded_vector_size, input_length=max_length,name="embedding"))
model.add(Flatten())
model.add(Dense(1, activation='sigmoid'))

In [11]:
X = padded_reviews
y = sentiment

In [12]:
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
print(model.summary())

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, 3, 4)              120       
_________________________________________________________________
flatten_1 (Flatten)          (None, 12)                0         
_________________________________________________________________
dense_1 (Dense)              (None, 1)                 13        
Total params: 133
Trainable params: 133
Non-trainable params: 0
_________________________________________________________________
None


In [13]:
model.fit(X, y, epochs=50, verbose=0)

In [14]:
# evaluate the model
loss, accuracy = model.evaluate(X, y)
accuracy

1/1 [==============================] - 0s 129ms/step - loss: 0.6216 - accuracy: 1.0000


1.0

In [15]:
weights = model.get_layer('embedding').get_weights()[0]
len(weights)

30

In [16]:
weights[13]

array([ 0.03771987, -0.00954071, -0.01757815,  0.01110882], dtype=float32)

In [17]:
weights[4]

array([ 0.05188975, -0.04306065, -0.00782154,  0.04557914], dtype=float32)

In [18]:
weights[16]

array([ 0.04202526,  0.01033118, -0.00455114, -0.03164717], dtype=float32)